; Arrow tile.
.db $FF,$00,$00,$00,$FF,$18,$00,$00,$FF,$0C,$00,$00,$FF,$7E,$00,$00,$FF,$7E,$00,$00,$FF,$0C,$00,$00,$FF,$18,$00,$00,$FF,$00,$00,$00
; Tile number 0x001
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$44,$44,$FF,$FF,$00,$00,$FF,$FF,$11,$11,$FF
; Tile number 0x002
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FF,$00,$00,$FF,$FE,$00,$01,$FF,$E0,$00,$1F,$FF,$80,$00,$7F,$FF,$C0,$00,$3F,$FF,$C0,$00,$3F,$FF
; Tile number 0x003
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FF,$00,$00,$FF,$01,$00,$FE,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF
; Tile number 0x004
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FC,$00,$03,$FF,$FC,$00,$03,$FF,$F8,$00,$07,$FF,$7C,$44,$C7,$FF,$3C,$00,$C3,$FF,$3F,$11,$D1,$FF
; Tile number 0x005
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$7F,$00,$80,$FF,$3F,$00,$C0,$FF,$3F,$00,$C0,$FF,$3F,$04,$C4,$FF,$7F,$00,$80,$FF,$FF,$11,$11,$FF
; Tile number 0x006
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FC,$44,$47,$FF,$FC,$00,$03,$FF,$FE,$10,$11,$FF
; Tile number 0x007
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FF,$00,$00,$FF,$F0,$00,$0F,$FF,$80,$00,$7F,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$03,$01,$FD,$FF
; Tile number 0x008
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FF,$00,$00,$FF,$1F,$00,$E0,$FF,$07,$00,$F8,$FF,$03,$00,$FC,$FF,$03,$00,$FC,$FF,$C3,$01,$3D,$FF
; Tile number 0x009
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$F9,$00,$06,$FF,$E1,$00,$1E,$FF,$81,$00,$7E,$FF,$01,$00,$FE,$FF,$01,$00,$FE,$FF,$C1,$01,$3F,$FF
; Tile number 0x00A
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$FE,$00,$01,$FF,$F8,$00,$07,$FF,$E0,$00,$1F,$FF,$C0,$40,$7F,$FF,$C0,$00,$3F,$FF,$F0,$10,$1F,$FF
; Tile number 0x00B
.db $FF,$00,$00,$FF,$FF,$40,$40,$FF,$7F,$00,$80,$FF,$7F,$00,$80,$FF,$7F,$00,$80,$FF,$7F,$44,$C4,$FF,$7F,$00,$80,$FF,$7F,$11,$91,$FF
; Tile number 0x00C
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$FF,$00,$00,$FF,$FF,$55,$55,$FF,$FF,$00,$00,$FF,$FF,$45,$45,$FF,$FF,$00,$00,$FF,$FF,$55,$55,$FF
; Tile number 0x00D
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$FF,$00,$00,$FF,$FF,$55,$51,$FF,$FF,$0C,$00,$FF,$FF,$5D,$45,$FF,$FF,$18,$00,$FF,$EF,$7D,$55,$FF
; Tile number 0x00E
.db $C0,$00,$3F,$FF,$E0,$40,$5F,$FF,$D0,$00,$2F,$FF,$F0,$50,$5F,$FF,$F8,$00,$07,$FF,$F8,$40,$47,$FF,$F8,$00,$07,$FF,$F8,$50,$57,$FF
; Tile number 0x00F
.db $78,$00,$87,$FF,$7C,$44,$C7,$FF,$3C,$00,$C3,$FF,$3C,$14,$D7,$FF,$3C,$00,$C3,$FF,$3C,$04,$C7,$FF,$3C,$00,$C3,$FF,$3C,$14,$D7,$FF
; Tile number 0x010
.db $3F,$00,$C0,$FF,$1F,$04,$E4,$FF,$1F,$00,$E0,$FF,$1C,$14,$F7,$FF,$10,$00,$EF,$FF,$10,$00,$EF,$FF,$1C,$00,$E3,$FF,$1C,$14,$F7,$FF
; Tile number 0x011
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$BF,$00,$40,$FF,$3F,$15,$D5,$FF,$3F,$00,$C0,$FF,$3F,$05,$C5,$FF,$3F,$00,$C0,$FF,$1E,$14,$F5,$FF
; Tile number 0x012
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$F9,$00,$06,$FF,$C0,$40,$7F,$FF,$80,$00,$7F,$FF,$04,$04,$FF,$FF,$0C,$00,$F3,$FF,$0E,$04,$F5,$FF
; Tile number 0x013
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$0F,$00,$F0,$FF,$0F,$05,$F5,$FF,$0F,$00,$F0,$FF,$0F,$05,$F5,$FF,$0F,$00,$F0,$FF,$0E,$04,$F5,$FF
; Tile number 0x014
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$0F,$00,$F0,$FF,$0F,$05,$F5,$FF,$0F,$00,$F0,$FF,$0F,$05,$F5,$FF,$0F,$00,$F0,$FF,$0F,$05,$F5,$FF
; Tile number 0x015
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$FF,$00,$00,$FF,$F0,$50,$5F,$FF,$C0,$00,$3F,$FF,$80,$00,$7F,$FF,$00,$00,$FF,$FF,$0C,$04,$F7,$FF
; Tile number 0x016
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$FE,$00,$01,$FF,$3E,$14,$D5,$FF,$0E,$00,$F1,$FF,$0E,$04,$F5,$FF,$1E,$00,$E1,$FF,$3E,$14,$D5,$FF
; Tile number 0x017
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$01,$01,$FF,$FF,$03,$00,$FC,$FF,$07,$05,$FD,$FF
; Tile number 0x018
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$3F,$00,$C0,$FF,$0F,$05,$F5,$FF,$07,$00,$F8,$FF,$0F,$05,$F5,$FF,$3F,$00,$C0,$FF,$FF,$55,$55,$FF
; Tile number 0x019
.db $FE,$00,$01,$FF,$FF,$44,$44,$FF,$FE,$00,$01,$FF,$FF,$55,$55,$FF,$FF,$00,$00,$FF,$FF,$45,$45,$FF,$FF,$00,$00,$FF,$FF,$55,$55,$FF
; Tile number 0x01A
.db $07,$00,$F8,$FF,$03,$00,$FC,$FF,$83,$00,$7C,$FF,$C3,$41,$7D,$FF,$C2,$00,$3D,$FF,$C0,$40,$7F,$FF,$C0,$00,$3F,$FF,$E1,$41,$5F,$FF
; Tile number 0x01B
.db $C7,$00,$38,$FF,$8F,$04,$74,$FF,$8F,$00,$70,$FF,$07,$05,$FD,$FF,$03,$00,$FC,$FF,$01,$01,$FF,$FF,$C1,$00,$3E,$FF,$E0,$40,$5F,$FF
; Tile number 0x01C
.db $FF,$00,$00,$FF,$FF,$44,$44,$FF,$FE,$00,$01,$FF,$F8,$50,$57,$FF,$E0,$00,$1F,$FF,$C1,$41,$7F,$FF,$C3,$00,$3C,$FF,$83,$01,$7D,$FF
; Tile number 0x01D
.db $FB,$00,$04,$FF,$E3,$40,$5C,$FF,$03,$00,$FC,$FF,$03,$01,$FD,$FF,$03,$00,$FC,$FF,$03,$01,$FD,$FF,$03,$00,$FC,$FF,$83,$01,$7D,$FF
; Tile number 0x01E
.db $C1,$00,$3E,$FF,$C1,$40,$7E,$FF,$C1,$00,$3E,$FF,$C1,$41,$7F,$FF,$C1,$00,$3E,$FF,$C1,$41,$7F,$FF,$C1,$00,$3E,$FF,$C1,$41,$7F,$FF
; Tile number 0x01F
.db $F0,$00,$0F,$FF,$F0,$40,$4F,$FF,$F0,$00,$0F,$FF,$F0,$50,$5F,$FF,$F0,$00,$0F,$FF,$F0,$40,$4F,$FF,$F0,$00,$0F,$FF,$F0,$50,$5F,$FF
; Tile number 0x020
.db $7F,$00,$80,$FF,$7F,$44,$C4,$FF,$7F,$00,$80,$FF,$7F,$55,$D5,$FF,$7F,$00,$80,$FF,$7F,$45,$C5,$FF,$7F,$00,$80,$FF,$7F,$55,$D5,$FF
; Tile number 0x021
.db $FF,$80,$80,$FF,$FF,$55,$55,$FF,$FF,$00,$00,$FF,$FF,$55,$55,$FF,$FF,$88,$88,$FF,$FF,$55,$55,$FF,$FF,$22,$22,$FF,$FF,$55,$55,$FF
; Tile number 0x022
.db $FF,$80,$80,$FF,$FF,$55,$55,$FF,$FF,$00,$00,$FF,$FF,$55,$54,$FF,$FF,$8A,$88,$FE,$FE,$57,$55,$FF,$FC,$27,$23,$FF,$FC,$5B,$53,$FB
; Tile number 0x023
.db $EF,$D8,$90,$DF,$DF,$6D,$25,$EF,$9F,$E8,$60,$EF,$9F,$75,$65,$7F,$1F,$F8,$E8,$FF,$1F,$F5,$E4,$FF,$1F,$F2,$E0,$FE,$3E,$D5,$C1,$DD
; Tile number 0x024
.db $FF,$84,$80,$FF,$FF,$5D,$45,$FF,$FF,$38,$00,$FF,$EF,$5D,$15,$DF,$DF,$A8,$20,$AF,$9F,$75,$65,$7F,$1F,$F2,$E2,$FF,$3F,$D5,$C5,$DF
; Tile number 0x025
.db $FF,$80,$80,$FF,$FF,$55,$55,$FF,$FF,$00,$00,$FF,$FF,$55,$51,$FF,$FF,$8C,$80,$FF,$FF,$5D,$45,$FF,$EF,$7A,$12,$FF,$DF,$AD,$25,$AF
; Tile number 0x026
.db $F8,$80,$87,$FF,$F8,$50,$57,$FF,$F8,$00,$07,$FF,$F8,$50,$57,$FF,$FC,$88,$8B,$FF,$FC,$54,$57,$FF,$FC,$20,$23,$FF,$FC,$54,$57,$FF
; Tile number 0x027
.db $38,$00,$C7,$FF,$30,$10,$DF,$FF,$20,$00,$DF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$01,$01,$FF,$FF,$07,$02,$FA,$FF,$7F,$55,$D5,$FF
; Tile number 0x028
.db $3C,$00,$C3,$FF,$3C,$14,$D7,$FF,$3C,$00,$C3,$FF,$7C,$54,$D7,$FF,$FC,$88,$8B,$FF,$FC,$54,$57,$FF,$FC,$20,$23,$FF,$FC,$54,$57,$FF
; Tile number 0x029
.db $1E,$00,$E1,$FF,$1E,$14,$F5,$FF,$1E,$00,$E1,$FF,$1E,$14,$F5,$FF,$1E,$08,$E9,$FF,$1F,$15,$F5,$FF,$1F,$02,$E2,$FF,$1F,$15,$F5,$FF
; Tile number 0x02A
.db $0E,$00,$F1,$FF,$06,$04,$FD,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$80,$00,$7F,$FF,$C0,$40,$7F,$FF
; Tile number 0x02B
.db $0E,$00,$F1,$FF,$0E,$04,$F5,$FF,$0E,$00,$F1,$FF,$0E,$04,$F5,$FF,$0E,$08,$F9,$FF,$0F,$05,$F5,$FF,$0F,$02,$F2,$FF,$0F,$05,$F5,$FF
; Tile number 0x02C
.db $18,$00,$E7,$FF,$18,$10,$F7,$FF,$10,$00,$EF,$FF,$01,$01,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$C0,$40,$7F,$FF
; Tile number 0x02D
.db $7E,$00,$81,$FF,$FE,$54,$55,$FF,$9E,$00,$61,$FF,$8E,$04,$75,$FF,$06,$00,$F9,$FF,$0E,$04,$F5,$FF,$1E,$02,$E3,$FF,$7F,$55,$D5,$FF
; Tile number 0x02E
.db $07,$00,$F8,$FF,$07,$05,$FD,$FF,$07,$00,$F8,$FF,$07,$05,$FD,$FF,$07,$00,$F8,$FF,$07,$05,$FD,$FF,$07,$02,$FA,$FF,$0F,$05,$F5,$FF
; Tile number 0x02F
.db $E0,$80,$9F,$FF,$E0,$40,$5F,$FF,$E0,$00,$1F,$FF,$F0,$50,$5F,$FF,$F0,$80,$8F,$FF,$F0,$50,$5F,$FF,$F8,$20,$27,$FF,$F9,$51,$57,$FF
; Tile number 0x030
.db $E0,$80,$9F,$FF,$C0,$40,$7F,$FF,$80,$00,$7F,$FF,$01,$01,$FF,$FF,$03,$00,$FC,$FF,$07,$05,$FD,$FF,$3F,$22,$E2,$FF,$FF,$55,$55,$FF
; Tile number 0x031
.db $83,$80,$FC,$FF,$81,$01,$7F,$FF,$80,$00,$7F,$FF,$80,$00,$7F,$FF,$C0,$80,$BF,$FF,$C0,$40,$7F,$FF,$E0,$20,$3F,$FF,$F0,$50,$5F,$FF
; Tile number 0x032
.db $83,$80,$FC,$FF,$83,$01,$7D,$FF,$03,$00,$FC,$FF,$03,$01,$FD,$FF,$03,$00,$FC,$FF,$03,$01,$FD,$FF,$03,$02,$FE,$FF,$03,$01,$FD,$FF
; Tile number 0x033
.db $C1,$80,$BE,$FF,$C1,$41,$7F,$FF,$C1,$00,$3E,$FF,$C0,$40,$7F,$FF,$C0,$80,$BF,$FF,$C0,$40,$7F,$FF,$E0,$20,$3F,$FF,$E0,$40,$5F,$FF
; Tile number 0x034
.db $F0,$80,$8F,$FF,$F0,$50,$5F,$FF,$F0,$00,$0F,$FF,$F0,$50,$5F,$FF,$F0,$80,$8F,$FF,$F0,$50,$5F,$FF,$F8,$20,$27,$FF,$F8,$50,$57,$FF
; Tile number 0x035
.db $7F,$00,$80,$FF,$7F,$55,$D5,$FF,$7F,$00,$80,$FF,$3F,$15,$D5,$FF,$3F,$08,$C8,$FF,$3F,$15,$D5,$FF,$3F,$22,$E2,$FF,$3F,$15,$D5,$FF
; Tile number 0x036
.db $FF,$88,$88,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF
; Tile number 0x037
.db $FF,$88,$88,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$57,$54,$FF,$FE,$BD,$A1,$FD,$F0,$7F,$0F,$FF
; Tile number 0x038
.db $F8,$9F,$87,$FF,$F0,$5F,$4F,$FF,$E0,$BF,$9F,$FF,$E0,$5F,$1F,$DF,$C0,$FF,$3F,$FF,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x039
.db $38,$DF,$C7,$DF,$30,$DF,$CF,$DF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x03A
.db $3F,$DB,$C8,$DF,$3E,$F5,$D1,$FD,$38,$FF,$C7,$FF,$30,$EF,$CF,$EF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE
; Tile number 0x03B
.db $1F,$F8,$E8,$FF,$3F,$D5,$C5,$DF,$3F,$EA,$CA,$FF,$7F,$B5,$95,$BF,$7F,$CA,$8A,$FF,$FF,$57,$14,$7F,$FF,$7C,$00,$7C,$F0,$0F,$0F,$0F
; Tile number 0x03C
.db $FF,$88,$88,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF,$FF,$9A,$8A,$FF,$FF,$F5,$05,$FF,$7F,$AA,$8A,$BF,$FF,$55,$15,$7F
; Tile number 0x03D
.db $FC,$88,$8B,$FF,$FC,$54,$57,$FF,$FB,$AA,$AE,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF
; Tile number 0x03E
.db $1F,$08,$E8,$FF,$1F,$15,$F5,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF
; Tile number 0x03F
.db $FE,$88,$89,$FF,$FE,$54,$55,$FF,$3E,$2A,$EB,$FF,$1E,$14,$F5,$FF,$0E,$0A,$FB,$FF,$0E,$04,$F5,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF
; Tile number 0x040
.db $0F,$08,$F8,$FF,$0F,$05,$F5,$FF,$0F,$0A,$FA,$FF,$0F,$05,$F5,$FF,$0F,$0A,$FA,$FF,$0F,$05,$F5,$FF,$1F,$0A,$EA,$FF,$1F,$15,$F5,$FF
; Tile number 0x041
.db $FF,$88,$88,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$57,$54,$FF
; Tile number 0x042
.db $FF,$88,$88,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$BF,$A0,$FF,$FF,$F5,$1F,$EA
; Tile number 0x043
.db $FF,$88,$88,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$EA,$2A,$FF,$FF,$7D,$C5,$BF
; Tile number 0x044
.db $E0,$80,$9F,$FF,$E0,$40,$5F,$FF,$E0,$A0,$BF,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF
; Tile number 0x045
.db $F8,$88,$8F,$FF,$F8,$50,$57,$FF,$F8,$A8,$AF,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF
; Tile number 0x046
.db $3F,$08,$C8,$FF,$3F,$15,$D5,$FF,$3F,$2A,$EA,$FF,$FF,$55,$55,$FF,$FF,$8A,$8A,$FF,$FF,$55,$55,$FF,$FF,$AA,$AA,$FF,$FF,$55,$55,$FF
; Tile number 0x047
.db $FF,$EA,$EA,$FF,$FF,$55,$55,$FF,$FF,$BA,$BA,$FF,$FF,$55,$55,$FF,$FF,$EE,$EE,$FF,$FF,$55,$55,$FF,$FF,$BB,$BB,$FF,$FF,$55,$55,$FF
; Tile number 0x048
.db $FF,$EA,$EA,$FF,$FF,$55,$55,$FF,$FF,$BA,$BA,$FF,$FF,$55,$55,$FF,$FF,$EF,$EE,$FF,$FF,$56,$54,$FE,$FE,$BB,$B9,$FF,$FE,$55,$51,$FD
; Tile number 0x049
.db $FF,$EB,$E8,$FF,$FF,$5E,$50,$FE,$F8,$F7,$87,$F7,$E0,$DF,$1F,$DF,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x04A
.db $C0,$BF,$3F,$BF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FE,$00,$FF,$FF,$F8,$00,$FF,$FF,$F0,$00,$FF,$FF,$C0,$00,$FF,$FF,$80
; Tile number 0x04B
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$F0,$00,$FF,$FF,$80,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$18,$DB,$C3,$18
; Tile number 0x04C
.db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
; Tile number 0x04D
.db $01,$FF,$FE,$01,$01,$FF,$FE,$01,$01,$FF,$FE,$01,$00,$FE,$FE,$00,$00,$FE,$FE,$00,$30,$BF,$8F,$30,$68,$EB,$83,$68,$84,$87,$33,$B4
; Tile number 0x04E
.db $00,$FF,$FF,$FF,$81,$7F,$7E,$7F,$83,$7E,$7C,$7F,$87,$FF,$79,$FF,$8F,$F6,$72,$F7,$9F,$ED,$65,$EF,$9F,$FB,$6B,$FF,$FF,$B5,$15,$BF
; Tile number 0x04F
.db $FF,$EA,$6A,$FF,$FF,$55,$55,$FF,$FF,$BA,$BA,$FF,$FF,$55,$55,$FF,$FF,$EE,$EE,$FF,$FF,$55,$55,$FF,$FF,$BB,$BB,$FF,$FF,$55,$55,$FF
; Tile number 0x050
.db $80,$80,$FF,$FF,$E0,$40,$5F,$FF,$FF,$BA,$BA,$FF,$FF,$55,$55,$FF,$FF,$EE,$EE,$FF,$FF,$55,$55,$FF,$FF,$BB,$BB,$FF,$FF,$55,$55,$FF
; Tile number 0x051
.db $3F,$2A,$EA,$FF,$FF,$55,$55,$FF,$FF,$BA,$BA,$FF,$FF,$55,$55,$FF,$FF,$EE,$EE,$FF,$FF,$55,$55,$FF,$FF,$BB,$BB,$FF,$FF,$55,$55,$FF
; Tile number 0x052
.db $FF,$EA,$EA,$FF,$FF,$55,$55,$FF,$FF,$BA,$BA,$FF,$FF,$55,$55,$FF,$FF,$EE,$EE,$FF,$FF,$54,$54,$FE,$FE,$B9,$B9,$FD,$FC,$53,$53,$F3
; Tile number 0x053
.db $FF,$EA,$EA,$FF,$FF,$55,$55,$FF,$FF,$BB,$B8,$FF,$FF,$55,$53,$FE,$FF,$DE,$C7,$D9,$FF,$35,$1F,$2A,$7F,$FA,$BF,$C5,$FF,$D5,$7F,$AA
; Tile number 0x054
.db $FF,$FC,$E3,$FF,$FF,$75,$1F,$EA,$FF,$AA,$7F,$D5,$FF,$55,$FF,$AA,$FF,$E8,$FF,$17,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA
; Tile number 0x055
.db $FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$A0,$FF,$5F,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$20,$FF,$DF,$FF,$55,$FF,$AA
; Tile number 0x056
.db $FF,$87,$F8,$7F,$FF,$55,$FF,$AA,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA,$FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA
; Tile number 0x057
.db $FF,$EA,$EA,$FF,$FF,$F5,$15,$FF,$FF,$1A,$E2,$FF,$FF,$57,$F9,$AF,$FF,$01,$FE,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$11,$FF,$EE
; Tile number 0x058
.db $FF,$EA,$EA,$FF,$FF,$55,$55,$FF,$FF,$BA,$BA,$FF,$FF,$55,$55,$FF,$FF,$EE,$EE,$FF,$FF,$D5,$15,$FF,$FF,$3B,$DB,$FF,$FF,$15,$E5,$FF
; Tile number 0x059
.db $FF,$EE,$EE,$FF,$FF,$55,$55,$FF,$FF,$FF,$FF,$FF,$FF,$55,$55,$FF,$FF,$FF,$FF,$FF,$FF,$55,$55,$FF,$FF,$FF,$FF,$FF,$FF,$55,$55,$FF
; Tile number 0x05A
.db $FC,$EF,$EB,$FF,$FC,$57,$53,$FF,$FC,$FB,$F3,$FB,$F8,$5F,$57,$FF,$F8,$FF,$F7,$FF,$F8,$5F,$57,$FF,$F8,$FF,$F7,$FF,$F8,$57,$47,$F7
; Tile number 0x05B
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FE,$00,$FF,$FF,$FE,$00,$FF,$FF,$FC,$00,$FF,$FF,$FC,$00,$FF,$FF,$F8,$00,$FF,$FF,$F8,$00,$FF,$FF,$F8
; Tile number 0x05C
.db $26,$E7,$C9,$2E,$41,$C1,$9C,$5D,$43,$C3,$BC,$7D,$4C,$CC,$B3,$70,$53,$D3,$AC,$63,$57,$D7,$A8,$67,$57,$D7,$88,$47,$64,$E4,$99,$45
; Tile number 0x05D
.db $00,$FF,$FF,$00,$00,$FE,$FE,$00,$00,$7E,$7E,$00,$80,$FE,$7E,$80,$80,$FE,$7E,$80,$80,$BE,$3E,$80,$80,$BE,$3E,$80,$C0,$FF,$3F,$C0
; Tile number 0x05E
.db $82,$83,$79,$FA,$F2,$F3,$0D,$8E,$8A,$8A,$74,$86,$E9,$E9,$16,$E7,$F5,$F5,$0A,$F3,$B5,$B5,$0A,$B3,$95,$95,$4A,$D3,$FD,$FD,$00,$F9
; Tile number 0x05F
.db $7F,$6E,$2E,$7F,$7F,$55,$15,$7F,$7F,$FF,$BF,$7F,$7F,$D5,$95,$7F,$7F,$FF,$BF,$7F,$7F,$D5,$95,$7F,$7F,$FF,$BF,$7F,$3F,$B5,$95,$3F
; Tile number 0x060
.db $FF,$EE,$EE,$FF,$FF,$55,$55,$FF,$FF,$FE,$FE,$FE,$FE,$55,$55,$FD,$FC,$F3,$F3,$F3,$F0,$4F,$4F,$EF,$E0,$DF,$DF,$DF,$C0,$3F,$3F,$3F
; Tile number 0x061
.db $F1,$CF,$CE,$CF,$C3,$3F,$3D,$BE,$87,$7F,$7B,$7C,$0F,$FD,$F7,$FA,$0F,$FE,$F7,$F9,$1F,$F5,$EF,$FA,$3F,$FF,$DF,$E0,$3F,$F5,$DF,$EA
; Tile number 0x062
.db $FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FA,$FF,$05,$FF,$55,$FF,$AA,$FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FA,$FF,$05,$FF,$55,$FF,$AA
; Tile number 0x063
.db $FF,$E8,$FF,$17,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$A8,$FF,$57,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA
; Tile number 0x064
.db $FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$20,$FF,$DF,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA
; Tile number 0x065
.db $FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$50,$FF,$AF,$FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$51,$FF,$AE
; Tile number 0x066
.db $FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$40,$FF,$BF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF
; Tile number 0x067
.db $FF,$0E,$F6,$FF,$FF,$45,$F9,$BF,$FF,$03,$FD,$FF,$FF,$11,$FE,$EF,$FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$15,$FF,$EA
; Tile number 0x068
.db $FF,$EE,$EE,$FF,$FF,$55,$55,$FF,$FF,$FF,$FF,$FF,$FF,$55,$55,$FF,$FF,$FF,$7F,$FF,$FF,$D5,$55,$FF,$FF,$7F,$BF,$FF,$FF,$75,$D5,$BF
; Tile number 0x069
.db $FF,$FF,$FF,$FF,$FF,$DD,$DD,$FF,$FF,$FF,$FF,$FF,$FF,$75,$75,$FF,$FF,$FF,$FF,$FF,$FF,$DD,$DD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x06A
.db $F8,$F7,$E7,$F7,$F8,$D7,$C7,$F7,$F8,$FF,$E7,$FF,$F9,$7E,$76,$FE,$F9,$FF,$F6,$FF,$FB,$DD,$D4,$FD,$FB,$FD,$F4,$FD,$FB,$FD,$F4,$FD
; Tile number 0x06B
.db $00,$FF,$FF,$F8,$18,$E3,$E3,$E0,$FC,$7D,$01,$7C,$80,$BF,$3F,$80,$20,$6F,$4F,$20,$40,$FF,$BF,$40,$70,$FF,$8F,$70,$40,$67,$27,$40
; Tile number 0x06C
.db $24,$A4,$98,$24,$37,$F7,$C8,$27,$3F,$FF,$C0,$3F,$00,$C1,$C1,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
; Tile number 0x06D
.db $C0,$FF,$3F,$C0,$C0,$DF,$1F,$C0,$C1,$DF,$1E,$C1,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FE,$FE,$00,$01,$FF,$FE,$01
; Tile number 0x06E
.db $7F,$7F,$00,$7F,$C2,$DB,$19,$C2,$01,$7D,$7C,$01,$01,$FF,$FE,$01,$01,$FF,$FE,$01,$02,$FA,$F8,$02,$3C,$3D,$01,$3C,$C0,$CF,$0F,$C0
; Tile number 0x06F
.db $3F,$FF,$DF,$3F,$3F,$FD,$DD,$3F,$3F,$FF,$DF,$3F,$3F,$F5,$D5,$3F,$3F,$FF,$DF,$3F,$3F,$FD,$DD,$3F,$1F,$DF,$CF,$1F,$1F,$FF,$EF,$1F
; Tile number 0x070
.db $FF,$FF,$FF,$FF,$FF,$DD,$DD,$FF,$FF,$FF,$FF,$FF,$FF,$75,$75,$FF,$FF,$FF,$FF,$FF,$FF,$DD,$DD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FC,$FF
; Tile number 0x071
.db $FF,$FE,$FE,$FE,$FE,$DD,$DD,$FD,$FC,$FB,$FB,$FB,$F8,$77,$77,$F7,$F0,$EF,$EF,$EF,$E0,$DF,$DF,$DF,$C0,$BF,$BF,$BF,$80,$7F,$7F,$7F
; Tile number 0x072
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FF,$FE,$FF,$01,$FF,$FE,$FF
; Tile number 0x073
.db $7F,$FE,$BF,$C1,$7F,$D5,$BF,$EA,$7F,$FF,$BF,$C0,$FF,$D5,$7F,$AA,$FF,$FF,$7F,$80,$FF,$DD,$7F,$A2,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA
; Tile number 0x074
.db $FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$A0,$FF,$5F,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$A0,$FF,$5F,$FF,$55,$FF,$AA
; Tile number 0x075
.db $FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$51,$FF,$AE,$FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA
; Tile number 0x076
.db $FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$11,$FF,$EE,$FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA
; Tile number 0x077
.db $FF,$00,$FF,$FF,$FF,$44,$FF,$BB,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA,$FF,$00,$FF,$FF,$FF,$45,$FF,$BA,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA
; Tile number 0x078
.db $FF,$3F,$DF,$FF,$FF,$5D,$ED,$BF,$FF,$1F,$EF,$FF,$FF,$55,$E5,$BF,$FF,$0F,$F7,$FF,$FF,$5D,$F5,$AF,$FF,$0F,$F7,$FF,$FF,$5F,$F7,$AF
; Tile number 0x079
.db $FF,$FF,$FF,$FF,$FF,$FD,$FD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FB,$FF,$FB,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x07A
.db $FF,$FF,$FF,$FF,$FF,$FD,$FD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FB,$FF,$FA,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x07B
.db $F9,$F7,$E6,$F7,$F1,$FE,$EE,$FE,$F0,$EF,$CF,$EF,$E0,$DF,$9F,$DF,$C0,$BF,$3F,$BF,$E0,$9F,$1F,$9F,$FE,$FD,$01,$FD,$FE,$FF,$F9,$FF
; Tile number 0x07C
.db $00,$3F,$3F,$00,$80,$FF,$7F,$80,$E0,$63,$03,$60,$3C,$DF,$C3,$DC,$0C,$F7,$F3,$F4,$0C,$F7,$F3,$F4,$04,$FF,$FB,$FC,$04,$FF,$FB,$FC
; Tile number 0x07D
.db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$20,$AF,$8F,$20,$1F,$DF,$C0,$1F,$00,$F8,$F8,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
; Tile number 0x07E
.db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$BF,$BF,$00,$40,$7F,$3F,$40,$80,$BF,$3F,$80,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
; Tile number 0x07F
.db $1F,$FF,$EF,$1F,$1F,$FD,$ED,$1F,$0F,$EF,$E7,$0F,$0F,$FF,$F7,$0F,$0F,$FF,$F7,$0F,$0B,$FF,$F3,$0F,$0F,$EF,$E7,$0F,$1F,$DF,$CF,$1F
; Tile number 0x080
.db $FF,$FF,$FF,$FF,$FF,$FD,$FD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FB,$FF,$FB,$FF,$FF,$FF,$FE,$FF,$FF,$FF,$F8,$FF
; Tile number 0x081
.db $FE,$FD,$F8,$FF,$FF,$F8,$F0,$FF,$F7,$F8,$E0,$FF,$FF,$F0,$E0,$FF,$FF,$E1,$C0,$FF,$DE,$E1,$80,$FF,$FF,$80,$00,$FF,$FF,$00,$00,$FF
; Tile number 0x082
.db $FF,$FF,$7F,$FF,$FF,$FD,$65,$FF,$EF,$F7,$43,$FF,$FF,$C7,$03,$FF,$7F,$87,$03,$FF,$FB,$0F,$00,$FF,$ED,$1E,$00,$FF,$F7,$18,$00,$FF
; Tile number 0x083
.db $FF,$FF,$FF,$FF,$FF,$FD,$FD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FB,$FF,$3B,$FF,$FF,$3F,$1F,$FF,$FF,$3F,$1F,$FF
; Tile number 0x084
.db $FF,$FE,$FE,$FE,$FE,$FD,$FD,$FD,$FE,$FD,$FD,$FD,$FC,$FB,$FB,$FB,$F8,$F7,$F7,$F7,$F0,$EF,$EF,$EF,$E0,$DF,$DF,$DF,$E0,$DF,$DF,$DF
; Tile number 0x085
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x086
.db $01,$FF,$FE,$FF,$01,$FF,$FE,$FF,$01,$FF,$FE,$FF,$03,$FF,$FD,$FE,$03,$FF,$FD,$FE,$03,$FF,$FD,$FE,$03,$FF,$FD,$FE,$03,$FF,$FD,$FE
; Tile number 0x087
.db $FF,$FE,$FF,$01,$FF,$D5,$FF,$2A,$FF,$FF,$FF,$00,$FF,$75,$FF,$8A,$FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$75,$FF,$8A
; Tile number 0x088
.db $FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FA,$FF,$05,$FF,$55,$FF,$AA,$FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA
; Tile number 0x089
.db $FF,$E8,$FF,$17,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$EA,$FF,$15,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA
; Tile number 0x08A
.db $FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$A0,$FF,$5F,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA
; Tile number 0x08B
.db $FF,$80,$FF,$7F,$FF,$55,$FF,$AA,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$22,$FF,$DD,$FF,$55,$FF,$AA
; Tile number 0x08C
.db $FF,$00,$FF,$FF,$FF,$54,$FF,$AB,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA
; Tile number 0x08D
.db $FF,$00,$FF,$FF,$FF,$55,$FF,$AA,$FF,$00,$FF,$FF,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$02,$FF,$FD,$FF,$55,$FF,$AA
; Tile number 0x08E
.db $FF,$8F,$F7,$7F,$FF,$55,$F9,$AF,$FF,$27,$FB,$DF,$FF,$57,$FB,$AF,$FF,$8F,$FB,$77,$FF,$57,$FB,$AF,$FF,$2F,$FB,$D7,$FF,$57,$FB,$AF
; Tile number 0x08F
.db $FF,$FF,$FF,$FF,$BB,$FF,$BB,$FF,$FF,$FF,$FF,$FF,$AE,$FF,$AE,$FF,$FF,$FF,$FF,$FF,$BB,$FF,$BB,$FF,$FF,$FF,$FF,$FF,$AA,$FF,$AA,$FF
; Tile number 0x090
.db $FE,$FD,$F9,$FD,$BC,$FF,$BB,$FF,$F8,$FF,$F7,$FF,$B8,$F7,$A7,$F7,$FF,$F0,$C0,$F0,$BF,$FF,$A0,$FF,$FF,$FF,$FF,$FF,$AA,$FF,$AA,$FF
; Tile number 0x091
.db $04,$FF,$FB,$FC,$04,$FD,$F9,$FC,$04,$FD,$F9,$FC,$04,$FD,$F9,$FC,$06,$FB,$F9,$FA,$FE,$FE,$00,$FE,$E3,$FF,$C0,$FF,$DF,$E0,$80,$FF
; Tile number 0x092
.db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$00,$00,$00,$FF,$FF,$00,$FF,$FF,$00,$00,$FF
; Tile number 0x093
.db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$07,$07,$00,$07,$F8,$FF,$00,$FF,$FF,$00,$00,$FF
; Tile number 0x094
.db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$07,$E7,$E0,$07,$F9,$FE,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF
; Tile number 0x095
.db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$01,$FD,$FC,$01,$1E,$DF,$C0,$1F,$E7,$F8,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF
; Tile number 0x096
.db $3F,$BF,$9F,$3F,$FB,$FF,$3B,$FF,$3F,$FF,$07,$FF,$F6,$0F,$02,$FF,$FF,$07,$03,$FF,$FF,$07,$03,$FF,$FF,$07,$03,$FF,$F6,$0F,$02,$FF
; Tile number 0x097
.db $FF,$FF,$FF,$FF,$BB,$FF,$BB,$FF,$FF,$FF,$FF,$FF,$AE,$FF,$AE,$FF,$FF,$FF,$FF,$FF,$BB,$FF,$BA,$FF,$FE,$FE,$F8,$FF,$BF,$FF,$A3,$FF
; Tile number 0x098
.db $FB,$FC,$E0,$FF,$AF,$F0,$80,$FF,$FF,$C0,$00,$FF,$FF,$80,$00,$FF,$BF,$C0,$00,$FF,$DF,$E0,$00,$FF,$EF,$F0,$C0,$FF,$FF,$F0,$E0,$FF
; Tile number 0x099
.db $FF,$00,$00,$FF,$FF,$01,$00,$FF,$F7,$0F,$01,$FF,$DE,$3B,$00,$FF,$FF,$01,$00,$FF,$FD,$03,$00,$FF,$FF,$07,$01,$FF,$FA,$FF,$02,$FF
; Tile number 0x09A
.db $FF,$7F,$3F,$FF,$BB,$FF,$3B,$FF,$FF,$FF,$FF,$FF,$AE,$FF,$AE,$FF,$FF,$FF,$FF,$FF,$BB,$FF,$BB,$FF,$FF,$FF,$FF,$FF,$AA,$FF,$AA,$FF
; Tile number 0x09B
.db $FF,$FF,$FF,$FF,$BB,$FF,$BB,$FF,$FF,$FF,$FF,$FF,$AF,$FE,$AE,$FE,$FE,$FD,$FD,$FD,$BA,$FD,$B9,$FD,$FC,$FB,$FB,$FB,$AC,$FB,$AB,$FB
; Tile number 0x09C
.db $C0,$BF,$BF,$BF,$80,$7F,$7F,$7F,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x09D
.db $01,$FF,$FE,$FF,$01,$FF,$FE,$FF,$01,$FF,$FE,$FF,$01,$FF,$FE,$FF,$07,$F9,$F8,$F9,$18,$E7,$E7,$E7,$20,$DF,$DF,$DF,$C0,$3F,$3F,$3F
; Tile number 0x09E
.db $FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$F5,$FF,$0A,$FF,$FF,$FF,$00,$FF,$DD,$7F,$A2,$FF,$FF,$7F,$80,$FF,$FF,$7F,$80
; Tile number 0x09F
.db $FF,$FE,$FF,$01,$FF,$D5,$FF,$2A,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA,$FF,$FE,$FF,$01,$FF,$D5,$FF,$2A,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA
; Tile number 0x0A0
.db $FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FA,$FF,$05,$FF,$55,$FF,$AA,$FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FB,$FF,$04,$FF,$55,$FF,$AA
; Tile number 0x0A1
.db $FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$A2,$FF,$5D,$FF,$55,$FF,$AA,$FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA
; Tile number 0x0A2
.db $FF,$88,$FF,$77,$FF,$55,$FF,$AA,$FF,$A2,$FF,$5D,$FF,$55,$FF,$AA,$FF,$8A,$FF,$75,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA
; Tile number 0x0A3
.db $FF,$AF,$FB,$57,$FF,$57,$FB,$AF,$FF,$AF,$FB,$57,$FE,$5F,$F6,$AF,$FF,$AF,$F7,$5F,$FB,$5F,$F3,$AF,$FF,$BF,$EF,$5F,$FA,$5F,$EA,$BF
; Tile number 0x0A4
.db $FF,$FF,$FF,$FF,$AB,$FF,$AB,$FF,$FF,$FF,$FF,$FF,$AA,$FF,$AA,$FF,$F7,$FF,$F7,$FF,$AA,$FF,$AA,$FF,$FF,$FF,$FF,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0A5
.db $FF,$C0,$80,$FF,$BF,$C0,$00,$FF,$FF,$80,$00,$FF,$BF,$C0,$00,$FF,$FF,$C0,$80,$FF,$BF,$FF,$80,$FF,$FF,$F0,$EF,$F0,$BF,$FF,$AF,$FF
; Tile number 0x0A6
.db $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$FF,$00,$FF,$FF,$3F,$FF,$3F,$FF,$FF,$FF,$FF
; Tile number 0x0A7
.db $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$8F,$7F,$00,$FF,$FF,$F3,$0F,$F3,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0A8
.db $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FE,$01,$00,$FF,$CF,$3F,$00,$FF,$FB,$FB,$03,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0A9
.db $FF,$00,$00,$FF,$F3,$0F,$00,$FF,$7F,$FF,$01,$FF,$DF,$DF,$1F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0AA
.db $9F,$7F,$07,$FF,$EB,$FF,$0B,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$C0,$FF,$FF,$DF,$FF,$DF,$FF,$DF,$FF,$DF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF
; Tile number 0x0AB
.db $FF,$FF,$FF,$FF,$AB,$FF,$A8,$FF,$FF,$FF,$C3,$FF,$FF,$FF,$3F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0AC
.db $FF,$FF,$9F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0AD
.db $EF,$E8,$E0,$FF,$F7,$F4,$F0,$FF,$FD,$FE,$F8,$FF,$FF,$FE,$FC,$FF,$FE,$FF,$FC,$FF,$FF,$FF,$FE,$FF,$FF,$FF,$FE,$FF,$FE,$FF,$FC,$FF
; Tile number 0x0AE
.db $FD,$03,$00,$FF,$FF,$07,$01,$FF,$FF,$0F,$07,$FF,$FA,$1F,$0A,$FF,$F7,$3F,$17,$FF,$AA,$7F,$0A,$FF,$FF,$FF,$3F,$FF,$AA,$FF,$2A,$FF
; Tile number 0x0AF
.db $F8,$F7,$F7,$F7,$A8,$F7,$A7,$F7,$F0,$EF,$EF,$EF,$B0,$EF,$AF,$EF,$E0,$DF,$DF,$DF,$A0,$DF,$9F,$DF,$C0,$BF,$BF,$BF,$C0,$BF,$BF,$BF
; Tile number 0x0B0
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE,$02,$FD,$FD,$FD
; Tile number 0x0B1
.db $01,$FE,$FE,$FE,$06,$F9,$F9,$F9,$08,$F7,$F7,$F7,$30,$CF,$CF,$CF,$40,$BF,$BF,$BF,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x0B2
.db $FF,$FF,$7F,$80,$7F,$FD,$BF,$C2,$7F,$FF,$BF,$C0,$3F,$FF,$DF,$E0,$3F,$FF,$DF,$E0,$1F,$FD,$EF,$F2,$1F,$FF,$EF,$F0,$0F,$FF,$F7,$F8
; Tile number 0x0B3
.db $FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$F5,$FF,$0A,$FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$F7,$FF,$08
; Tile number 0x0B4
.db $FF,$FE,$FF,$01,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$D5,$FF,$2A,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA
; Tile number 0x0B5
.db $FF,$EA,$FF,$15,$FF,$55,$FF,$AA,$FF,$BA,$FF,$45,$FF,$55,$FF,$AA,$FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$BB,$FF,$44,$FF,$55,$FF,$AA
; Tile number 0x0B6
.db $FF,$EA,$FF,$15,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$BB,$FF,$44,$FF,$55,$FF,$AA
; Tile number 0x0B7
.db $FF,$EA,$FF,$15,$FF,$55,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$BF,$FF,$40,$FF,$55,$FE,$AB
; Tile number 0x0B8
.db $FF,$FF,$EF,$1F,$EB,$7F,$CB,$BF,$FF,$BF,$DF,$7F,$EA,$7F,$AA,$FF,$F7,$FF,$B7,$7F,$AA,$FF,$2A,$FF,$FF,$FF,$7F,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0B9
.db $77,$FF,$77,$FF,$AA,$FF,$AA,$FF,$5D,$FF,$5D,$FF,$AA,$FF,$AA,$FF,$77,$FF,$77,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0BA
.db $7F,$FF,$6F,$FF,$BF,$FF,$AF,$FF,$5F,$FF,$4F,$FF,$BF,$FF,$AF,$FF,$7F,$FF,$6F,$FF,$AF,$EF,$8F,$FF,$7F,$FF,$5F,$FF,$BF,$FF,$9F,$FF
; Tile number 0x0BB
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0BC
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BF,$FF,$FF,$FF,$BF,$FF,$DF,$DF,$9F,$FF
; Tile number 0x0BD
.db $FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF
; Tile number 0x0BE
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$FF,$FE,$FF,$E0,$FF
; Tile number 0x0BF
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$FF,$FF,$FF,$F9,$FF,$FA,$FF,$C2,$FF,$D5,$FF,$15,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0C0
.db $F7,$F7,$F3,$FF,$FA,$FF,$E2,$FF,$FD,$FF,$9D,$FF,$AA,$FF,$2A,$FF,$77,$FF,$77,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0C1
.db $77,$FF,$77,$FF,$AA,$FF,$AA,$FF,$5D,$FE,$5C,$FE,$AB,$FE,$AA,$FE,$77,$FE,$76,$FE,$AA,$FD,$A9,$FD,$56,$FD,$55,$FD,$AC,$FB,$AB,$FB
; Tile number 0x0C2
.db $80,$7F,$7F,$7F,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE
; Tile number 0x0C3
.db $04,$FB,$FB,$FB,$08,$F7,$F7,$F7,$10,$EF,$EF,$EF,$20,$DF,$DF,$DF,$40,$BF,$BF,$BF,$40,$BF,$BF,$BF,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF
; Tile number 0x0C4
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE,$0E,$F1,$F1,$F1
; Tile number 0x0C5
.db $07,$FF,$FB,$FC,$03,$FF,$FD,$FE,$01,$FF,$FE,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$1F,$E0,$E0,$E0,$E0,$1F,$1F,$1F,$00,$FF,$FF,$FF
; Tile number 0x0C6
.db $FF,$FF,$FF,$00,$FF,$FD,$FF,$02,$FF,$FF,$FF,$00,$FF,$FF,$7F,$80,$7F,$FF,$BF,$C0,$FF,$3D,$1F,$22,$1F,$FF,$E7,$F8,$07,$FF,$FB,$FC
; Tile number 0x0C7
.db $FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$F5,$FF,$0A,$FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00
; Tile number 0x0C8
.db $FF,$FE,$FF,$01,$FF,$D5,$FF,$2A,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$77,$FF,$88
; Tile number 0x0C9
.db $FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA
; Tile number 0x0CA
.db $FF,$EE,$FF,$11,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$55,$FF,$AA,$FF,$FF,$FF,$00,$FF,$57,$FC,$AB
; Tile number 0x0CB
.db $FF,$EF,$FD,$13,$FE,$57,$FA,$AF,$FD,$FF,$F5,$0F,$FA,$5F,$EA,$BF,$F7,$FF,$D7,$3F,$EA,$7F,$AA,$FF,$D5,$FF,$55,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0CC
.db $57,$FF,$57,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$AA,$FF,$11,$FF,$11,$FF,$AA,$FF,$AA,$FF,$54,$FF,$54,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0CD
.db $7F,$FF,$5F,$FF,$BF,$FF,$9F,$FF,$7F,$FF,$5F,$FF,$BF,$FF,$9F,$FF,$3F,$FF,$1F,$FF,$BF,$FF,$9F,$FF,$7F,$FF,$5F,$FF,$BF,$FF,$9F,$FF
; Tile number 0x0CE
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BF,$FF,$DF,$DF,$9F,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$EF,$FF
; Tile number 0x0CF
.db $BF,$BF,$9F,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$FF,$FF,$DF,$FF,$EF,$EF,$CF,$FF,$FF,$FF,$EF,$FF,$FF,$FF,$EF,$FF
; Tile number 0x0D0
.db $FF,$FF,$DC,$FF,$FE,$FF,$C2,$FF,$F5,$FF,$D5,$FF,$EA,$FF,$CA,$FF,$B1,$BF,$91,$FF,$EA,$FF,$AA,$FF,$D4,$FF,$94,$FF,$EA,$FF,$AA,$FF
; Tile number 0x0D1
.db $F7,$FF,$17,$FF,$AA,$FF,$AA,$FF,$55,$FF,$55,$FF,$AA,$FF,$AA,$FF,$11,$FF,$11,$FF,$AA,$FF,$AA,$FF,$54,$FF,$54,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0D2
.db $54,$FB,$53,$FB,$A8,$F7,$A7,$F7,$58,$F7,$57,$F7,$A8,$F7,$A7,$F7,$10,$EF,$0F,$EF,$B0,$EF,$AF,$EF,$50,$EF,$4F,$EF,$A0,$DF,$9F,$DF
; Tile number 0x0D3
.db $02,$FD,$FD,$FD,$04,$FB,$FB,$FB,$04,$FB,$FB,$FB,$08,$F7,$F7,$F7,$10,$EF,$EF,$EF,$10,$EF,$EF,$EF,$20,$DF,$DF,$DF,$40,$BF,$BF,$BF
; Tile number 0x0D4
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$03,$FC,$FC,$FC,$04,$FB,$FB,$FB
; Tile number 0x0D5
.db $00,$FF,$FF,$FF,$01,$FE,$FE,$FE,$06,$F9,$F9,$F9,$18,$E7,$E7,$E7,$20,$DF,$DF,$DF,$C0,$3F,$3F,$3F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x0D6
.db $30,$CF,$CF,$CF,$C0,$3F,$3F,$3F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x0D7
.db $03,$FF,$FC,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x0D8
.db $FF,$FF,$FF,$00,$FF,$FD,$3F,$C2,$3F,$FF,$C7,$F8,$07,$FF,$F8,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x0D9
.db $FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FF,$00,$FF,$FF,$3F,$C0,$3F,$FF,$C0,$FF,$01,$FE,$FE,$FE,$0E,$F1,$F0,$F1,$7A,$8F,$8A,$8F
; Tile number 0x0DA
.db $FF,$FF,$FF,$00,$FF,$DD,$FF,$22,$FF,$FF,$FE,$01,$FE,$FF,$E0,$1F,$F1,$FF,$11,$FF,$EA,$3F,$2A,$3F,$54,$FF,$54,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0DB
.db $FF,$FF,$F3,$0F,$FA,$FF,$CA,$3F,$D5,$FF,$15,$FF,$AA,$FF,$AA,$FF,$11,$FF,$11,$FF,$AA,$FF,$AA,$FF,$54,$FF,$54,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0DC
.db $11,$FF,$11,$FF,$AA,$FF,$AA,$FF,$04,$FF,$04,$FF,$AA,$FF,$AA,$FF,$11,$FF,$11,$FF,$AA,$FF,$AA,$FF,$00,$FF,$00,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0DD
.db $3F,$FF,$1F,$FF,$BF,$FF,$9F,$FF,$3F,$FF,$1F,$FF,$DF,$DF,$9F,$FF,$7F,$FF,$3F,$FF,$FF,$FF,$BF,$FF,$7F,$FF,$3F,$FF,$FF,$FF,$BF,$FF
; Tile number 0x0DE
.db $EF,$EF,$E7,$FF,$FF,$FF,$F7,$FF,$FF,$FF,$FB,$FF,$FB,$FB,$F9,$FF,$FD,$FD,$FC,$FF,$FF,$FF,$FE,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0DF
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$7F,$7F,$7F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$BF,$FF
; Tile number 0x0E0
.db $F7,$F7,$E7,$FF,$FF,$FF,$F7,$FF,$FF,$FF,$FB,$FF,$FD,$FD,$F9,$FF,$FF,$FF,$FD,$FF,$FD,$FD,$FC,$FF,$FE,$FE,$FE,$FF,$FF,$FF,$FF,$FF
; Tile number 0x0E1
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$7F,$FF,$7F,$7F,$3F,$FF
; Tile number 0x0E2
.db $D1,$FF,$91,$FF,$EA,$FF,$AA,$FF,$C4,$FF,$84,$FF,$EA,$FF,$AA,$FF,$D1,$FF,$91,$FF,$6A,$7F,$2A,$FF,$80,$FF,$00,$FF,$AA,$FF,$2A,$FF
; Tile number 0x0E3
.db $20,$DF,$1F,$DF,$A0,$DF,$9F,$DF,$40,$BF,$3F,$BF,$C1,$BE,$BE,$BE,$41,$BE,$3E,$BE,$C2,$BD,$BD,$BD,$82,$7D,$7D,$7D,$84,$7B,$7B,$7B
; Tile number 0x0E4
.db $40,$BF,$BF,$BF,$80,$7F,$7F,$7F,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE,$02,$FD,$FD,$FD,$04,$FB,$FB,$FB,$08,$F7,$F7,$F7
; Tile number 0x0E5
.db $08,$F7,$F7,$F7,$30,$CF,$CF,$CF,$40,$BF,$BF,$BF,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x0E6
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE,$0E,$F1,$F0,$F1,$7A,$8F,$8A,$8F
; Tile number 0x0E7
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$07,$F8,$F8,$F8,$39,$C7,$C1,$C7,$EA,$3F,$2A,$3F,$00,$FF,$00,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0E8
.db $03,$FC,$FC,$FC,$1E,$E3,$E2,$E3,$E4,$1F,$04,$1F,$AA,$FF,$AA,$FF,$11,$FF,$11,$FF,$AA,$FF,$AA,$FF,$00,$FF,$00,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0E9
.db $91,$7F,$11,$7F,$AA,$FF,$AA,$FF,$04,$FF,$04,$FF,$AA,$FF,$AA,$FF,$11,$FF,$11,$FF,$AA,$FF,$AA,$FF,$00,$FF,$00,$FF,$AA,$FF,$AA,$FF
; Tile number 0x0EA
.db $00,$FF,$00,$FF,$2A,$FF,$2A,$FF,$00,$FF,$00,$FF,$AA,$FF,$AA,$FF,$00,$FF,$00,$FF,$22,$FF,$22,$FF,$00,$FF,$00,$FF,$88,$FF,$88,$FF
; Tile number 0x0EB
.db $7F,$FF,$3F,$FF,$7F,$FF,$3F,$FF,$7F,$FF,$3F,$FF,$FF,$FF,$BF,$FF,$7F,$FF,$3F,$FF,$BF,$BF,$3F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$7F,$FF
; Tile number 0x0EC
.db $BF,$BF,$9F,$FF,$DF,$DF,$CF,$FF,$EF,$EF,$E7,$FF,$FB,$FB,$F3,$FF,$FD,$FD,$F9,$FF,$FF,$FF,$FD,$FF,$FF,$FF,$FE,$FF,$FE,$FE,$FE,$FF
; Tile number 0x0ED
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$7F,$FF
; Tile number 0x0EE
.db $DF,$DF,$9F,$FF,$FF,$FF,$CF,$FF,$EF,$EF,$E7,$FF,$F7,$F7,$F3,$FF,$FA,$FA,$F8,$FF,$FF,$FF,$FE,$FF,$FE,$FE,$FE,$FF,$FD,$FD,$FC,$FF
; Tile number 0x0EF
.db $80,$FF,$00,$FF,$AA,$FF,$2A,$FF,$80,$FF,$00,$FF,$AA,$FF,$2A,$FF,$80,$FF,$00,$FF,$62,$7F,$22,$FF,$E0,$BF,$00,$FF,$E8,$3F,$08,$FF
; Tile number 0x0F0
.db $00,$FF,$00,$FF,$2B,$FE,$2A,$FE,$01,$FE,$00,$FE,$AB,$FE,$AA,$FE,$01,$FE,$00,$FE,$22,$FD,$21,$FD,$02,$FD,$01,$FD,$8A,$FD,$89,$FD
; Tile number 0x0F1
.db $84,$7B,$7B,$7B,$08,$F7,$F7,$F7,$08,$F7,$F7,$F7,$10,$EF,$EF,$EF,$10,$EF,$EF,$EF,$21,$DE,$DE,$DE,$22,$DD,$DD,$DD,$42,$BD,$BD,$BD
; Tile number 0x0F2
.db $10,$EF,$EF,$EF,$20,$DF,$DF,$DF,$40,$BF,$BF,$BF,$40,$BF,$BF,$BF,$80,$7F,$7F,$7F,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF
; Tile number 0x0F3
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE,$06,$F9,$F8,$F9
; Tile number 0x0F4
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$03,$FC,$FC,$FC,$0C,$F3,$F0,$F3,$72,$8F,$82,$8F,$80,$7F,$00,$7F,$88,$FF,$88,$FF
; Tile number 0x0F5
.db $03,$FC,$FC,$FC,$1E,$E3,$E2,$E3,$60,$9F,$80,$9F,$AA,$7F,$2A,$7F,$00,$FF,$00,$FF,$22,$FF,$22,$FF,$00,$FF,$00,$FF,$88,$FF,$88,$FF
; Tile number 0x0F6
.db $80,$7F,$00,$7F,$2A,$FF,$2A,$FF,$00,$FF,$00,$FF,$AA,$FF,$AA,$FF,$00,$FF,$00,$FF,$22,$FF,$22,$FF,$00,$FF,$00,$FF,$88,$FF,$88,$FF
; Tile number 0x0F7
.db $00,$FF,$00,$FF,$22,$FF,$22,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF
; Tile number 0x0F8
.db $00,$FF,$00,$FF,$22,$FF,$22,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$01,$FF,$00,$FF
; Tile number 0x0F9
.db $FF,$FF,$7F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$7F,$FF,$7F,$7F,$7F,$FF
; Tile number 0x0FA
.db $7F,$7F,$3F,$FF,$BF,$BF,$9F,$FF,$DF,$DF,$CF,$FF,$EF,$EF,$E7,$FF,$F7,$F7,$F3,$FF,$FB,$FB,$F9,$FF,$FD,$FD,$FC,$FF,$FF,$FF,$FE,$FF
; Tile number 0x0FB
.db $FB,$FA,$F8,$FF,$F7,$F4,$F0,$FF,$EF,$E8,$E0,$FF,$DF,$D0,$C0,$FF,$BF,$A0,$80,$FF,$FF,$C0,$80,$FF,$BF,$C0,$00,$FF,$7F,$80,$00,$FF
; Tile number 0x0FC
.db $F0,$1F,$00,$FF,$EA,$1F,$02,$FF,$F4,$0F,$00,$FF,$FA,$07,$00,$FF,$FD,$03,$00,$FF,$FD,$03,$00,$FF,$FF,$07,$00,$FF,$FF,$04,$00,$FF
; Tile number 0x0FD
.db $00,$FF,$00,$FF,$3F,$FF,$20,$FF,$30,$FF,$10,$E0,$40,$FF,$00,$C0,$80,$FF,$00,$80,$80,$FF,$80,$00,$DF,$FF,$10,$CF,$F0,$7F,$00,$FF
; Tile number 0x0FE
.db $00,$FF,$00,$FF,$A2,$FF,$22,$FF,$60,$FF,$00,$7F,$10,$FF,$00,$1F,$08,$FF,$00,$0F,$08,$FF,$00,$0F,$04,$FF,$00,$07,$82,$FF,$00,$83
; Tile number 0x0FF
.db $02,$FD,$01,$FD,$24,$FB,$23,$FB,$04,$FB,$03,$FB,$04,$FB,$03,$FB,$09,$F6,$06,$F6,$09,$F6,$06,$F6,$09,$F6,$06,$F6,$0A,$F5,$05,$F5
; Tile number 0x100
.db $44,$BB,$BB,$BB,$48,$B7,$B7,$B7,$88,$77,$77,$77,$90,$6F,$6F,$6F,$20,$DF,$DF,$DF,$20,$DF,$DF,$DF,$40,$BF,$BF,$BF,$41,$BE,$BE,$BE
; Tile number 0x101
.db $00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FE,$FE,$06,$F9,$F8,$F9,$08,$F7,$F0,$F7,$30,$CF,$C0,$CF,$C0,$3F,$00,$3F,$00,$FF,$00,$FF
; Tile number 0x102
.db $18,$E7,$E0,$E7,$62,$9F,$82,$9F,$80,$7F,$00,$7F,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF,$00,$FF
; Tile number 0x103
.db $00,$FF,$00,$FF,$00,$BB,$00,$FF,$00,$FF,$00,$FF,$00,$EF,$00,$FF,$00,$FF,$00,$FF,$00,$BB,$00,$FF,$00,$FF,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x104
.db $01,$FF,$00,$FF,$01,$BB,$00,$FF,$01,$FF,$00,$FF,$03,$EF,$01,$FF,$03,$FF,$01,$FF,$03,$BB,$01,$FF,$07,$FF,$03,$FF,$07,$AF,$03,$FF
; Tile number 0x105
.db $FD,$FD,$FC,$FF,$FE,$FF,$FC,$FF,$FF,$FF,$FE,$FF,$FE,$FE,$FE,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
; Tile number 0x106
.db $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$80,$00,$FF,$5F,$60,$00,$FF,$EF,$F0,$C0,$FF,$F7,$F8,$E0,$FF,$FB,$FC,$F0,$FF
; Tile number 0x107
.db $FF,$04,$00,$FF,$FF,$0E,$00,$FF,$FD,$13,$00,$FF,$FE,$11,$00,$FF,$FF,$10,$00,$FF,$FB,$7C,$00,$FF,$F5,$4E,$00,$FF,$FF,$43,$00,$FF
; Tile number 0x108
.db $F0,$1F,$00,$FF,$F0,$1E,$00,$FF,$F0,$1F,$00,$FF,$F0,$FF,$00,$FF,$C0,$7F,$00,$FF,$C0,$6E,$00,$FF,$C1,$7F,$00,$FF,$C1,$EB,$00,$FF
; Tile number 0x109
.db $46,$FF,$00,$C7,$44,$FF,$00,$C7,$44,$FF,$00,$C7,$44,$FF,$00,$C7,$48,$FF,$00,$CF,$98,$FB,$10,$8F,$98,$FF,$80,$1F,$36,$FE,$20,$17
; Tile number 0x10A
.db $0A,$F5,$05,$F5,$0A,$B5,$05,$F5,$15,$EA,$0A,$EA,$15,$EA,$0A,$EA,$16,$E9,$09,$E9,$1E,$A1,$01,$E1,$1D,$E2,$02,$E2,$3E,$80,$00,$C1
; Tile number 0x10B
.db $82,$7D,$7C,$7D,$8C,$73,$70,$73,$10,$EF,$E0,$EF,$20,$CF,$C0,$DF,$40,$BF,$80,$BF,$80,$3B,$00,$7F,$00,$FF,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x10C
.db $00,$FF,$00,$FF,$00,$AB,$00,$FF,$00,$FF,$00,$FF,$00,$AA,$00,$FF,$00,$FF,$00,$FF,$00,$AA,$00,$FF,$00,$FF,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x10D
.db $0B,$FB,$03,$FF,$0F,$AF,$07,$FF,$17,$F7,$07,$FF,$1F,$BF,$0F,$FF,$3F,$FF,$1F,$FF,$5F,$DF,$1F,$FF,$7F,$FF,$3F,$FF,$FF,$FF,$7F,$FF
; Tile number 0x10E
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$FF,$FD,$FD,$FC,$FF,$FE,$FF,$FC,$FF
; Tile number 0x10F
.db $FE,$FE,$F0,$FF,$F1,$FF,$E0,$FF,$E0,$FF,$C0,$FF,$C0,$D6,$80,$FF,$80,$FF,$00,$FF,$00,$56,$00,$FF,$00,$FF,$00,$FF,$00,$56,$00,$FF
; Tile number 0x110
.db $FF,$FF,$FF,$FF,$7F,$7F,$7F,$FF,$BF,$BF,$3F,$FF,$7F,$FF,$3F,$FF,$5F,$DF,$1F,$FF,$3F,$BF,$1F,$FF,$3F,$FF,$1F,$FF,$2F,$AF,$0F,$FF
; Tile number 0x111
.db $FD,$FE,$F8,$FF,$FB,$FA,$F8,$FF,$FF,$FE,$FC,$FF,$FB,$FA,$F8,$FF,$FD,$FE,$F8,$FF,$FD,$FE,$F8,$FF,$FD,$FE,$F8,$FF,$FF,$FF,$FC,$FF
; Tile number 0x112
.db $DF,$61,$00,$FF,$F7,$79,$00,$FF,$DE,$7F,$10,$CF,$E1,$7F,$20,$C1,$E0,$7F,$20,$C0,$F0,$3F,$10,$E0,$F8,$3F,$18,$E0,$DC,$DF,$0C,$F0
; Tile number 0x113
.db $03,$FF,$01,$FE,$02,$AF,$00,$FE,$04,$FF,$00,$FC,$98,$BF,$00,$F8,$61,$FF,$01,$60,$01,$FF,$00,$01,$02,$FF,$00,$03,$04,$FE,$00,$07
; Tile number 0x114
.db $21,$FF,$00,$21,$60,$FF,$40,$20,$C0,$FF,$80,$40,$C0,$FF,$00,$C0,$B0,$FF,$00,$F0,$0C,$AF,$04,$F8,$06,$FF,$00,$FE,$01,$AB,$00,$FF
; Tile number 0x115
.db $00,$FF,$00,$FF,$C0,$EB,$00,$FF,$30,$FF,$00,$3F,$08,$FA,$00,$0F,$06,$FF,$00,$07,$01,$FF,$00,$01,$00,$FF,$00,$00,$80,$FF,$80,$00
; Tile number 0x116
.db $00,$FF,$00,$FF,$00,$AB,$00,$FF,$00,$FF,$00,$FF,$00,$AA,$00,$FF,$00,$FF,$00,$FF,$00,$AA,$00,$FF,$C0,$FF,$00,$FF,$30,$FA,$00,$3F
; Tile number 0x117
.db $00,$FF,$00,$FF,$00,$AB,$00,$FF,$00,$FF,$00,$FF,$03,$AB,$00,$FF,$04,$FC,$00,$FC,$08,$A8,$00,$F8,$10,$F0,$00,$F0,$20,$A0,$00,$E0
; Tile number 0x118
.db $00,$FF,$00,$FF,$00,$AB,$00,$FF,$C0,$FF,$00,$FF,$30,$3A,$00,$3F,$0C,$0F,$00,$0F,$02,$02,$00,$03,$01,$01,$00,$01,$00,$00,$00,$00
; Tile number 0x119
.db $3C,$C3,$00,$C3,$3C,$83,$00,$C3,$38,$C7,$00,$C7,$30,$8A,$00,$CF,$70,$8F,$00,$8F,$60,$8A,$00,$9F,$E0,$9F,$00,$9F,$60,$0A,$00,$1F
; Tile number 0x11A
.db $00,$77,$00,$FF,$00,$AA,$00,$FF,$00,$DF,$00,$FF,$00,$AA,$00,$FF,$00,$77,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x11B
.db $00,$77,$00,$FF,$00,$AA,$00,$FF,$00,$DF,$00,$FF,$00,$AA,$00,$FF,$00,$77,$00,$FF,$01,$AB,$00,$FF,$03,$56,$01,$FF,$07,$AC,$03,$FF
; Tile number 0x11C
.db $01,$77,$00,$FF,$02,$AA,$00,$FF,$35,$FD,$01,$FF,$7B,$DB,$33,$EF,$FB,$8B,$73,$FF,$FF,$0F,$FB,$F7,$FD,$05,$F9,$FF,$FE,$02,$FC,$FF
; Tile number 0x11D
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$FE,$FE,$FF
; Tile number 0x11E
.db $FC,$FF,$F8,$FF,$F8,$FD,$F0,$FF,$E8,$EE,$E0,$FF,$F0,$F5,$E0,$FF,$E0,$FB,$C0,$FF,$C0,$D5,$80,$FF,$80,$AA,$00,$FF,$80,$D5,$00,$FF
; Tile number 0x11F
.db $00,$B9,$00,$FF,$00,$56,$00,$FF,$00,$FF,$00,$FF,$00,$56,$00,$FF,$00,$B9,$00,$FF,$00,$56,$00,$FF,$00,$A9,$00,$FF,$00,$56,$00,$FF
; Tile number 0x120
.db $1F,$DF,$0F,$FF,$1F,$BF,$0F,$FF,$1F,$7F,$0F,$FF,$0F,$AF,$07,$FF,$0F,$DF,$07,$FF,$0F,$AF,$07,$FF,$0F,$5F,$07,$FF,$0F,$AF,$07,$FF
; Tile number 0x121
.db $EF,$EF,$E1,$FE,$E9,$EB,$E0,$FF,$F8,$FF,$F0,$FF,$F8,$FA,$F0,$FF,$F8,$FF,$F0,$FF,$F4,$F6,$F0,$FF,$FC,$FD,$F8,$FF,$FC,$FE,$F8,$FF
; Tile number 0x122
.db $F8,$FF,$E0,$1F,$E0,$EA,$00,$FF,$00,$DF,$00,$FF,$00,$AA,$00,$FF,$00,$77,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x123
.db $C0,$FF,$00,$C0,$30,$BF,$10,$E0,$1C,$DF,$04,$F8,$06,$AF,$00,$FE,$01,$77,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x124
.db $08,$FF,$00,$0F,$06,$FE,$00,$07,$01,$FF,$00,$01,$03,$FF,$02,$01,$82,$FE,$80,$02,$C6,$FE,$04,$C2,$34,$7C,$10,$E4,$1C,$BC,$08,$F4
; Tile number 0x125
.db $41,$41,$00,$C0,$82,$82,$00,$80,$04,$04,$00,$00,$08,$08,$00,$00,$10,$10,$00,$00,$20,$20,$00,$00,$40,$40,$00,$00,$40,$40,$00,$00
; Tile number 0x126
.db $C0,$C0,$00,$00,$30,$30,$00,$00,$0C,$0C,$00,$00,$03,$03,$00,$00,$01,$00,$00,$00,$01,$00,$00,$00,$01,$00,$00,$00,$01,$00,$00,$00
; Tile number 0x127
.db $70,$17,$00,$1F,$C8,$0A,$00,$0F,$C6,$07,$00,$07,$C1,$01,$00,$01,$C0,$00,$00,$00,$E0,$60,$00,$00,$90,$10,$00,$00,$88,$08,$00,$00
; Tile number 0x128
.db $00,$77,$00,$FF,$00,$AA,$00,$FF,$00,$DF,$00,$FF,$00,$AA,$00,$FF,$80,$F7,$00,$FF,$60,$6A,$00,$7F,$10,$15,$00,$1F,$08,$0A,$00,$0F
; Tile number 0x129
.db $00,$57,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF,$00,$51,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x12A
.db $00,$57,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF,$00,$51,$00,$FF,$01,$AB,$00,$FF,$03,$56,$01,$FF,$07,$AE,$03,$FD
; Tile number 0x12B
.db $0F,$58,$07,$FF,$1F,$B0,$0F,$FF,$3F,$60,$1F,$FF,$7F,$C0,$3F,$FF,$FF,$80,$7F,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF
; Tile number 0x12C
.db $FF,$03,$FE,$FD,$FF,$01,$FF,$FE,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF
; Tile number 0x12D
.db $7F,$7F,$7F,$FF,$BF,$BF,$3F,$FF,$DF,$DF,$9F,$7F,$EF,$6F,$CF,$BF,$F7,$37,$E7,$DF,$FB,$0B,$F3,$FF,$FC,$04,$F8,$FF,$FF,$03,$FC,$FF
; Tile number 0x12E
.db $FD,$FD,$FC,$FF,$FA,$FB,$F8,$FF,$F4,$F6,$F0,$FF,$E8,$ED,$E0,$FF,$D0,$DA,$C0,$FF,$A0,$B5,$80,$FF,$C0,$EA,$00,$FF,$00,$55,$00,$FF
; Tile number 0x12F
.db $00,$BA,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF,$00,$8A,$00,$FF,$00,$55,$00,$FF,$00,$AA,$00,$FF,$00,$55,$00,$FF
; Tile number 0x130
.db $00,$B9,$00,$FF,$00,$56,$00,$FF,$00,$A9,$00,$FF,$00,$56,$00,$FF,$00,$89,$00,$FF,$00,$56,$00,$FF,$00,$A9,$00,$FF,$00,$56,$00,$FF
; Tile number 0x131
.db $07,$5F,$03,$FF,$07,$AF,$03,$FF,$07,$57,$03,$FF,$07,$AF,$03,$FF,$07,$47,$03,$FF,$03,$AB,$01,$FF,$03,$57,$01,$FF,$0F,$AF,$00,$FF
; Tile number 0x132
.db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FD,$FD,$FC,$FF,$FF,$FE,$E1,$FF,$FF,$F0,$1F,$EF
; Tile number 0x133
.db $FC,$FF,$F8,$FF,$FD,$FF,$F8,$FF,$FF,$FE,$F9,$FF,$EF,$E8,$E7,$FF,$BF,$B0,$8F,$FF,$FF,$C0,$3F,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF
; Tile number 0x134
.db $00,$57,$00,$FF,$80,$AA,$00,$FF,$80,$D5,$00,$FF,$80,$AA,$00,$FF,$C0,$51,$80,$FF,$C0,$6A,$80,$FF,$C0,$55,$80,$FF,$E0,$2A,$C0,$FF
; Tile number 0x135
.db $08,$58,$00,$F8,$08,$A8,$00,$F8,$11,$51,$00,$F0,$11,$B1,$00,$F0,$21,$61,$00,$E0,$22,$A2,$00,$E0,$22,$62,$00,$E0,$22,$A2,$00,$E0
; Tile number 0x136
.db $80,$80,$00,$00,$80,$80,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
; Tile number 0x137
.db $01,$00,$00,$00,$01,$00,$00,$00,$03,$00,$00,$00,$03,$00,$00,$00,$03,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
; Tile number 0x138
.db $04,$04,$00,$00,$02,$02,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
; Tile number 0x139
.db $08,$0F,$00,$0F,$10,$1A,$00,$1F,$10,$15,$00,$1F,$20,$2A,$00,$3F,$20,$31,$00,$3F,$40,$6A,$00,$7F,$40,$55,$00,$7F,$80,$AA,$00,$FF
; Tile number 0x13A
.db $00,$11,$00,$FF,$00,$AA,$00,$FF,$00,$44,$00,$FF,$01,$AB,$00,$FF,$01,$11,$00,$FF,$01,$AB,$00,$FF,$00,$00,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x13B
.db $0F,$1C,$07,$FB,$1F,$B8,$0F,$F7,$FF,$F0,$0F,$FF,$FF,$38,$EF,$D7,$FF,$0C,$F7,$FB,$FF,$06,$FB,$FD,$FF,$83,$7D,$FE,$FF,$C1,$7E,$BF
; Tile number 0x13C
.db $FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$80,$FF,$7F
; Tile number 0x13D
.db $FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF
; Tile number 0x13E
.db $FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FE,$FF,$FE,$06,$FC,$FB,$FC,$0D,$F8,$F7,$F8,$18,$F0,$EF,$F0,$35,$E0,$DF
; Tile number 0x13F
.db $80,$88,$00,$FF,$C0,$D5,$80,$7F,$80,$A2,$00,$FF,$00,$55,$00,$FF,$00,$88,$00,$FF,$00,$55,$00,$FF,$00,$00,$00,$FF,$00,$55,$00,$FF
; Tile number 0x140
.db $00,$88,$00,$FF,$00,$55,$00,$FF,$00,$22,$00,$FF,$00,$55,$00,$FF,$00,$88,$00,$FF,$00,$55,$00,$FF,$00,$00,$00,$FF,$00,$55,$00,$FF
; Tile number 0x141
.db $00,$88,$00,$FF,$00,$56,$00,$FF,$00,$21,$00,$FF,$00,$56,$00,$FF,$00,$88,$00,$FF,$00,$56,$00,$FF,$00,$00,$00,$FF,$00,$56,$00,$FF
; Tile number 0x142
.db $0F,$48,$07,$FF,$0F,$A8,$07,$FF,$07,$14,$03,$FF,$07,$AC,$03,$FF,$07,$44,$03,$FF,$03,$AA,$01,$FF,$03,$02,$01,$FF,$03,$AA,$01,$FF
; Tile number 0x143
.db $E0,$31,$C0,$FF,$E0,$2A,$C0,$FF,$F0,$34,$C0,$FF,$F0,$1A,$E0,$FF,$F0,$11,$E0,$FF,$F7,$1F,$E0,$FF,$FF,$08,$F7,$FF,$FF,$00,$FF,$FF
; Tile number 0x144
.db $00,$11,$00,$FF,$00,$AA,$00,$FF,$00,$44,$00,$FF,$00,$AA,$00,$FF,$C0,$D1,$00,$FF,$F0,$FA,$C0,$3F,$F8,$18,$F0,$EF,$FC,$0E,$F8,$F7
; Tile number 0x145
.db $00,$11,$00,$FF,$00,$AA,$00,$FF,$00,$44,$00,$FF,$00,$AA,$00,$FF,$00,$11,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x146
.db $42,$42,$00,$C0,$41,$C1,$00,$C0,$40,$40,$00,$C0,$40,$C0,$00,$C0,$20,$20,$00,$E0,$10,$B0,$00,$F0,$0C,$0C,$00,$FC,$02,$AA,$00,$FE
; Tile number 0x147
.db $00,$00,$00,$00,$00,$00,$00,$00,$80,$80,$00,$00,$60,$60,$00,$00,$10,$10,$00,$00,$0C,$0C,$00,$00,$03,$03,$00,$00,$00,$00,$00,$00
; Tile number 0x148
.db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$C0,$C0,$00,$00
; Tile number 0x149
.db $00,$00,$00,$00,$01,$01,$00,$01,$02,$02,$00,$03,$02,$02,$00,$03,$04,$05,$00,$07,$04,$06,$00,$07,$08,$08,$00,$0F,$10,$1A,$00,$1F
; Tile number 0x14A
.db $80,$91,$00,$FF,$00,$AA,$00,$FF,$00,$44,$00,$FF,$00,$AA,$00,$FF,$00,$11,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$AA,$00,$FF
; Tile number 0x14B
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$88,$00,$FF
; Tile number 0x14C
.db $7F,$60,$3F,$DF,$3F,$B0,$1F,$EF,$1F,$18,$0F,$F7,$0F,$AC,$07,$FB,$07,$06,$03,$FD,$03,$23,$01,$FE,$01,$01,$00,$FF,$00,$88,$00,$FF
; Tile number 0x14D
.db $FF,$C0,$7F,$BF,$FF,$60,$BF,$DF,$FF,$30,$DF,$EF,$FF,$18,$EF,$F7,$FF,$0C,$F7,$FB,$FF,$06,$FB,$FD,$FF,$83,$FD,$7E,$FF,$C1,$7E,$BF
; Tile number 0x14E
.db $FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$01,$FF,$FE,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$80,$FF,$7F
; Tile number 0x14F
.db $E0,$68,$C0,$BF,$C0,$D5,$80,$7F,$80,$80,$00,$FF,$C0,$D5,$80,$7F,$E0,$60,$C0,$BF,$E0,$31,$C0,$FF,$E0,$20,$C0,$FF,$F0,$14,$E0,$FF
; Tile number 0x150
.db $00,$08,$00,$FF,$00,$55,$00,$FF,$00,$00,$00,$FF,$00,$55,$00,$FF,$00,$00,$00,$FF,$00,$11,$00,$FF,$00,$00,$00,$FF,$00,$44,$00,$FF
; Tile number 0x151
.db $00,$08,$00,$FF,$00,$56,$00,$FF,$00,$00,$00,$FF,$00,$56,$00,$FF,$00,$00,$00,$FF,$00,$10,$00,$FF,$00,$00,$00,$FF,$00,$46,$00,$FF
; Tile number 0x152
.db $03,$07,$01,$FE,$01,$AB,$00,$FF,$01,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$88,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF
; Tile number 0x153
.db $FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$80,$7F,$FF,$FF,$80,$7F,$FF,$FF,$80,$7F,$FF,$7F,$40,$3F,$FF,$7F,$40,$3F,$FF
; Tile number 0x154
.db $FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$00,$FF,$FF,$FF,$07,$FC,$FB,$FF,$1E,$F3,$ED
; Tile number 0x155
.db $FC,$05,$F8,$FF,$FE,$02,$FC,$FF,$FE,$02,$FC,$FF,$FF,$07,$FC,$FB,$FF,$1F,$F3,$EC,$FF,$F0,$8F,$7F,$FF,$C0,$7F,$BF,$FF,$00,$FF,$FF
; Tile number 0x156
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$AA,$00,$FF,$80,$80,$00,$FF,$C0,$62,$80,$FF,$C0,$40,$80,$FF,$C0,$C8,$80,$7F
; Tile number 0x157
.db $01,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$88,$00,$FF
; Tile number 0x158
.db $80,$80,$00,$80,$40,$C0,$00,$C0,$30,$30,$00,$F0,$0C,$AC,$00,$FC,$03,$03,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$88,$00,$FF
; Tile number 0x159
.db $30,$30,$00,$00,$08,$08,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$C1,$C1,$00,$C1,$32,$32,$00,$F3,$0C,$8C,$00,$FF
; Tile number 0x15A
.db $20,$21,$00,$3F,$20,$2A,$00,$3F,$40,$40,$00,$7F,$80,$AA,$00,$FF,$80,$80,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$88,$00,$FF
; Tile number 0x15B
.db $00,$01,$00,$FF,$00,$A8,$03,$FF,$00,$00,$03,$FF,$00,$A8,$03,$FF,$00,$00,$03,$FF,$00,$20,$03,$FF,$00,$00,$03,$FF,$00,$88,$03,$FF
; Tile number 0x15C
.db $00,$01,$00,$FF,$00,$02,$F8,$FF,$00,$00,$9C,$FF,$00,$20,$8E,$FF,$00,$00,$8E,$FF,$00,$20,$8E,$FF,$00,$00,$9C,$FF,$00,$00,$F8,$FF
; Tile number 0x15D
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$80,$7E,$FF,$00,$00,$7E,$FF,$00,$02,$70,$FF,$00,$00,$70,$FF,$00,$88,$70,$FF
; Tile number 0x15E
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$A0,$1F,$FF,$00,$00,$3B,$FF,$00,$00,$73,$FF,$00,$00,$7F,$FF,$00,$88,$70,$FF
; Tile number 0x15F
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$A0,$0F,$FF,$00,$00,$9C,$FF,$00,$22,$9C,$FF,$00,$00,$9F,$FF,$00,$80,$0F,$FF
; Tile number 0x160
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$28,$87,$FF,$00,$00,$CE,$FF,$00,$20,$0E,$FF,$00,$00,$8F,$FF,$00,$08,$C7,$FF
; Tile number 0x161
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$2A,$C0,$FF,$00,$00,$60,$FF,$00,$22,$00,$FF,$00,$00,$C0,$FF,$00,$08,$E0,$FF
; Tile number 0x162
.db $00,$01,$00,$FF,$00,$A8,$03,$FF,$00,$00,$07,$FF,$00,$A0,$0E,$FF,$00,$00,$0E,$FF,$00,$20,$07,$FF,$00,$00,$03,$FF,$00,$88,$00,$FF
; Tile number 0x163
.db $00,$01,$00,$FF,$00,$0A,$F0,$FF,$00,$00,$38,$FF,$00,$82,$39,$FF,$00,$00,$00,$FF,$00,$02,$E0,$FF,$00,$00,$F0,$FF,$00,$80,$38,$FF
; Tile number 0x164
.db $00,$01,$00,$FF,$00,$0A,$E0,$FF,$00,$00,$E0,$FF,$00,$02,$F8,$FF,$00,$00,$E0,$FF,$00,$02,$E0,$FF,$00,$00,$E0,$FF,$00,$08,$E1,$FF
; Tile number 0x165
.db $00,$01,$00,$FF,$00,$AA,$00,$FF,$00,$00,$00,$FF,$00,$82,$7C,$FF,$00,$00,$CE,$FF,$00,$20,$0E,$FF,$00,$00,$FE,$FF,$00,$00,$CE,$FF
; Tile number 0x166
.db $00,$01,$00,$FF,$00,$82,$38,$FF,$00,$00,$38,$FF,$00,$80,$7E,$FF,$00,$00,$38,$FF,$00,$02,$38,$FF,$00,$00,$38,$FF,$00,$80,$38,$FF
; Tile number 0x167
.db $00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x168
.db $7F,$60,$3F,$DF,$3F,$30,$1F,$EF,$1F,$18,$0F,$F7,$0F,$0C,$07,$FB,$07,$06,$03,$FD,$03,$23,$01,$FE,$01,$01,$00,$FF,$00,$00,$00,$FF
; Tile number 0x169
.db $F0,$10,$E0,$FF,$F0,$11,$E0,$FF,$E0,$20,$C0,$FF,$E0,$20,$C0,$FF,$C0,$40,$80,$FF,$C0,$D1,$80,$7F,$80,$80,$00,$FF,$00,$00,$00,$FF
; Tile number 0x16A
.db $00,$00,$00,$FF,$00,$11,$00,$FF,$00,$00,$00,$FF,$00,$40,$00,$FF,$00,$00,$00,$FF,$00,$11,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x16B
.db $00,$00,$00,$FF,$00,$10,$00,$FF,$00,$00,$00,$FF,$00,$40,$00,$FF,$00,$00,$00,$FF,$00,$10,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x16C
.db $00,$00,$00,$FF,$00,$88,$00,$FF,$00,$00,$00,$FF,$00,$20,$00,$FF,$00,$00,$00,$FF,$00,$88,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x16D
.db $7F,$60,$3F,$DF,$3F,$A0,$1F,$FF,$3F,$20,$1F,$FF,$3F,$30,$1F,$EF,$1F,$13,$0E,$FD,$1F,$9E,$01,$FF,$1F,$18,$0F,$F7,$1F,$10,$0F,$FF
; Tile number 0x16E
.db $FF,$00,$FF,$FF,$FF,$07,$FC,$FB,$FF,$1E,$E3,$FD,$FF,$F8,$9F,$67,$FF,$C0,$7F,$BF,$FF,$00,$FF,$FF,$FF,$03,$FC,$FF,$FC,$1C,$E0,$FF
; Tile number 0x16F
.db $FF,$F8,$8F,$77,$FF,$C0,$7F,$BF,$FF,$00,$FF,$FF,$FF,$03,$FE,$FD,$FE,$1E,$F0,$EF,$F0,$72,$80,$FF,$80,$80,$00,$FF,$00,$00,$00,$FF
; Tile number 0x170
.db $FF,$03,$FE,$FD,$FE,$1E,$E0,$FF,$E0,$60,$80,$FF,$80,$88,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x171
.db $80,$80,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x172
.db $00,$00,$03,$FF,$00,$20,$03,$FF,$00,$00,$03,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x173
.db $00,$00,$80,$FF,$00,$22,$80,$FF,$00,$00,$80,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x174
.db $00,$00,$70,$FF,$00,$02,$70,$FF,$00,$00,$70,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x175
.db $00,$00,$70,$FF,$00,$02,$39,$FF,$00,$00,$1F,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x176
.db $00,$00,$01,$FF,$00,$22,$99,$FF,$00,$00,$0F,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x177
.db $00,$00,$C0,$FF,$00,$22,$CC,$FF,$00,$00,$87,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x178
.db $00,$00,$E0,$FF,$00,$02,$E0,$FF,$00,$00,$C0,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x179
.db $00,$00,$0E,$FF,$00,$20,$0E,$FF,$00,$00,$07,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x17A
.db $00,$00,$38,$FF,$00,$02,$70,$FF,$00,$00,$E0,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x17B
.db $00,$00,$E1,$FF,$00,$02,$E1,$FF,$00,$00,$78,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x17C
.db $00,$00,$CE,$FF,$00,$20,$CE,$FF,$00,$00,$FE,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x17D
.db $00,$00,$38,$FF,$00,$02,$38,$FF,$00,$00,$1E,$FF,$00,$08,$00,$FF,$00,$00,$00,$FF,$00,$22,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x17E
.db $00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x17F
.db $7F,$61,$3E,$DF,$3F,$3F,$1C,$E3,$1C,$1C,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x180
.db $1F,$10,$0F,$FF,$1F,$1B,$0E,$F5,$0E,$0E,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
; Tile number 0x181
.db $E0,$60,$80,$FF,$80,$80,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF,$00,$00,$00,$FF
